# Generated by Django 2.2.6 on 2019-11-11 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='categoery',
            field=models.CharField(default='', max_length=50),
        ),
    ]
